### ISSUE TITLE
Create User Window Too Damn High 

### ISSUE THREAD

**Issue by mateusduboli** [dcposch/scramble#89]
When you try to create a user, the modal-window is rendered to high, and the username field gets hidden.

I got it to work by changing the

``` css
.modal-content {
  position: absolute;  // Was relative
}
```

But I didn't managed to find where should I change it.

The file that declares this class, is the `style.css`, but it looks like the file is from  bootstrap, which I find to be a bad idea to change.

It used to be those `stly` files, but they're not in the Makefile targets anymore.

So, could you show me where I can change?
